Repository Chillibean/sites-api-specifications, pull requests merged in 2025-09, with the labels that each got.

#39 task/BAN-57 Endpoint to fetch asset information is not protected by any
  public/fullSchema.json
  public/refs/components/schemas/Asset.json
  public/refs/paths/accounts_{account_id}_sites_{site_number}_subjects_{subject_number}_study_events_{study_event_identifier}_study_procedures_{study_procedure_identifier}_assets_{asset_id}.json
Labels: enhancement, 4.1.0

#38 Release v4.1.0
  package-lock.json
  package.json
  public/fullSchema.json
  public/refs/components/schemas/Asset.json
  public/refs/components/schemas/StudyProcedure.json
  public/refs/paths/accounts_{account_id}_sites_{site_number}_subjects_{subject_number}_study_events_{study_event_identifier}_study_procedures_{study_procedure_identifier}_assets_{asset_id}.json
  public/schema.json
Labels: release, 4.1.0

#43 task/BAN-185 Update api specs study protocol to trial configuration
  public/fullSchema.json
  public/refs/components/schemas/Site.json
  public/refs/components/schemas/StudyEvent.json
  public/refs/components/schemas/StudyProcedure.json
  public/refs/components/schemas/StudyProtocolObjectName.json
  public/refs/components/schemas/TrialConfiguration.json
  public/refs/components/schemas/TrialConfigurationObjectName.json
  public/schema.json
Labels: 4.3.0
